module: "easymocap.smplmodel.body_model.SMPLlayer"
args:
  model_path: "data/smplx/smplx"
  model_type: "smplx"
  gender: "neutral"
  device: "cuda"
  regressor_path: "data/smplx/J_regressor_body25_smplx.txt"
  use_pose_blending: True
  use_shape_blending: True
  use_lbs: True
